import Head from "next/head";
import { useState, useEffect } from "react";
import { Button, Container } from "@mui/material";

export default function Home() {
  const [user, setUser] = useState<undefined | null | Object>(undefined);

  async function fetch_user() {
    return await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/user`, {
      credentials: "include",
    })
      .then((res) => (res.ok ? res.json() : null))
      .catch(() => null);
  }

  useEffect(() => {
    (async function () {
      let user = await fetch_user();
      setUser(user);
    })();
  }, []);

  async function logout_user() {
    await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/auth/logout`, {
      credentials: "include",
    });
    setUser(null);
  }

  function get_login_status(): JSX.Element {
    if (user != null)
      return (
        <>
          <div>
            <p>You are signed in. WELCOME</p>
          </div>
          <div>
            <Button variant="outlined" onClick={logout_user}>
              Log out
            </Button>
          </div>
        </>
      );
    else if (user === null)
      return (
        <>
          <div>
            <p>You are not signed in.</p>
          </div>
          <div>
            <Button
              variant="contained"
              href={`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/auth/login`}
            >
              Sign in
            </Button>
          </div>
        </>
      );
    else return <p>Loading...</p>;
  }

  return (
    <div>
      <Head>
        <title>ft_trancendence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <main>
          <h1>ft_tranceeeendence</h1>
          {get_login_status()}
        </main>
      </Container>
    </div>
  );
}
